{{- if .Values.crdUpgrade.enabled }}
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "crds/*.yaml" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liqo-crds.fullname" $ }}-{{ base $path | replace "_" "-" | replace "." "-" | replace "-yaml" "" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "liqo-crds.labels" $ | nindent 4 }}
    app.kubernetes.io/component: crd-content
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    {{- if not $.Values.crdUpgrade.keepResources }}
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
data:
  {{ base $path }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
{{- end }}
